<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\Relations\HasMany;

class User extends Authenticatable
{
    /** @use HasFactory<\Database\Factories\UserFactory> */
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'role',
        'phone',
        'is_active',
    ];

    /**
     * The attributes that should be hidden for serialization.
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * Get the attributes that should be cast.
     */
    protected function casts(): array
    {
        return [
            'email_verified_at' => 'datetime',
            'password' => 'hashed',
            'is_active' => 'boolean',
        ];
    }

    // ================================================================
    // Role Helper Methods
    // ================================================================

    /**
     * Check if user is a clinic administrator.
     */
    public function isAdmin(): bool
    {
        return $this->role === 'admin';
    }

    /**
     * Check if user is clinic staff (doctor/nurse/assistant).
     */
    public function isStaff(): bool
    {
        return $this->role === 'staff';
    }

    /**
     * Check if user is a patient.
     */
    public function isPatient(): bool
    {
        return $this->role === 'patient';
    }

    /**
     * Check if user has staff or admin access.
     */
    public function isStaffOrAdmin(): bool
    {
        return in_array($this->role, ['staff', 'admin']);
    }

    // ================================================================
    // Relationships
    // ================================================================

    /**
     * Queue entries where this user is the patient.
     */
    public function queueEntries(): HasMany
    {
        return $this->hasMany(QueueEntry::class, 'patient_id');
    }

    /**
     * Queue entries this staff member has served.
     */
    public function servedEntries(): HasMany
    {
        return $this->hasMany(QueueEntry::class, 'served_by');
    }

    /**
     * In-app notifications for this user.
     */
    public function appNotifications(): HasMany
    {
        return $this->hasMany(Notification::class);
    }

    /**
     * Audit log entries generated by this user.
     */
    public function auditLogs(): HasMany
    {
        return $this->hasMany(AuditLog::class);
    }

    // ================================================================
    // Query Scopes
    // ================================================================

    /**
     * Scope to filter by role.
     */
    public function scopeWithRole($query, string $role)
    {
        return $query->where('role', $role);
    }

    /**
     * Scope to return only active users.
     */
    public function scopeActive($query)
    {
        return $query->where('is_active', true);
    }

    /**
     * Get the user's unread notification count.
     */
    public function unreadNotificationsCount(): int
    {
        return $this->appNotifications()->whereNull('read_at')->count();
    }

    /**
     * Get the role display label.
     */
    public function getRoleLabelAttribute(): string
    {
        return match($this->role) {
            'admin'   => 'Administrator',
            'staff'   => 'Clinical Staff',
            'patient' => 'Patient',
            default   => ucfirst($this->role),
        };
    }
}
